# Generated by Django 5.2 on 2025-04-14 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordem_servico', '0001_initial'),
        ('peca', '0002_rename_fornecedor_id_peca_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.ordemservico')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peca.peca')),
            ],
        ),
    ]
