# Generated by Django 5.2 on 2025-04-14 22:09

import apps.core.utils
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(default=apps.core.utils.gerar_placa, max_length=8, validators=[apps.core.validators.validar_placa]),
        ),
    ]
