# Generated by Django 5.2 on 2025-04-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peca',
            old_name='fornecedor_id',
            new_name='fornecedor',
        ),
    ]
